development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: youmu_development
  pool: 5
  username: <%= Rails.application.secrets.database_username %>
  password: <%= Rails.application.secrets.database_password %>
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: youmu_test
  pool: 5
  username: <%= Rails.application.secrets.database_username %>
  password: <%= Rails.application.secrets.database_password %>
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: youmu_production
  pool: 5
  username: <%= Rails.application.secrets.database_username %>
  password: <%= Rails.application.secrets.database_password %>
  host: localhost
